#check root env-example before running
services:

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    restart: always  

  redpanda:
    image: docker.redpanda.com/redpandadata/redpanda:latest
    command:
      - redpanda
      - start
      - --mode dev-container
      - --smp 1
      - --memory 1G
      - --reserve-memory 0M
      - --overprovisioned
      - --kafka-addr internal://0.0.0.0:9092,external://0.0.0.0:19092
      - --advertise-kafka-addr internal://redpanda:9092,external://localhost:19092
    ports:
      - "19092:19092"
      - "9092:9092"
    restart: always

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090" 
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml   

  api-gateway: 
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - ./api-gateway/.env  
    environment:
      - "REDIS_HOST=redis"  
      - "REDIS_PORT=6379"  
      - "AUTH_SERVICE_URL=http://auth-service:8081"
      - "TRAIN_SERVICE_URL=http://train-service:8082"
      - "BUS_SERVICE_URL=http://bus-service:8083"
      - "FLIGHT_SERVICE_URL=http://flight-service:8084"
      - "CHAT_SERVICE_URL=http://chat-service:8086"
      - "QR_SERVICE_URL=http://qr-service:8087"
      - "FRONTEND_URL=${FRONTEND_URL}"
    depends_on:
      - redis

  auth-service:
    build: 
      context: ./auth-service
      dockerfile: Dockerfile
    expose:
      - 8081
    env_file:
     - ./auth-service/.env
    environment:
      DB_URL: ${AUTH_DB}
      REDIS_HOST: redis
      REDIS_PORT: 6379
    depends_on:
      - redis

  flight-service:
    build:
      context: ./flight-service
      dockerfile: Dockerfile    
    expose:
      - 8084
    env_file:
      - ./flight-service/.env
    environment:
      DB_URL: ${FLIGHT_DB}
      RUN_SEED_ON_BOOT: "true"
      # REDIS_HOST: redis
      # REDIS_PORT: 6379   
      REDIS_URL: redis:6379           
      KAFKA_BROKERS: redpanda:9092
      PAYMENT_SERVICE_GRPC_URL: payment-service:50051
    depends_on:
      - redis  
      - redpanda

  # train-service:
  #   build:
  #     context: ./train-service
  #     dockerfile: Dockerfile
  #   expose:
  #     - 8082
  #   env_file:
  #     - ./train-service/.env
  #   environment:
  #     DB_URL: ${TRAIN_DB}
  #     REDIS_HOST: redis
  #     REDIS_PORT: 6379
  #     KAFKA_BROKERS: redpanda:9092

  #   depends_on:
  #     - redis  
  #     - redpanda

  # bus-service:
  #   build:
  #     context: ./bus-service
  #     dockerfile: Dockerfile
  #   expose:
  #     - 8083
  #   env_file:
  #     - ./bus-service/.env
  #   environment:
  #     DB_URL: ${BUS_DB}
  #     REDIS_HOST: redis
  #     REDIS_PORT: 6379
  #     KAFKA_BROKERS: redpanda:9092

  #   depends_on:
  #     - redis
  #     - redpanda

  payment-service:
    build:
      context: ./payment-service
      dockerfile: Dockerfile
    ports:
      - "8085:8085"
      - "50051:50051"
    env_file:
      - ./payment-service/.env
    environment:
      - "KAFKA_BROKERS=redpanda:9092"
    depends_on:
      - redis
      - redpanda

  chat-service:
    build:
      context: ./chat-service
      dockerfile: Dockerfile
    expose:
      - 8086
    env_file:
      - ./chat-service/.env
    environment:
      DATABASE_URL: ${CHAT_DB}
    depends_on:
      - redis

  qr-service:
    build:
      context: ./qr-service
      dockerfile: Dockerfile
    expose:
      - 8087
